//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class citations
    {
        public int id { get; set; }
        public string citationnumber { get; set; }
        public Nullable<System.DateTime> citationdate { get; set; }
        public string citationcountry { get; set; }
        public string citationcourt { get; set; }
        public Nullable<System.DateTime> citationcomplydate { get; set; }
        public string citationvcn { get; set; }
        public string token { get; set; }
    }
}
