//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactform
    {
        public int id { get; set; }
        public string C_type { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string dlicense { get; set; }
        public string tickethelp { get; set; }
        public string citationno { get; set; }
        public Nullable<System.DateTime> citationdate { get; set; }
        public Nullable<System.DateTime> complydate { get; set; }
        public string conticket { get; set; }
        public string vcnumber { get; set; }
        public string city { get; set; }
        public string info { get; set; }
    }
}
