//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class fleetservices
    {
        public int id { get; set; }
        public string doyouearn { get; set; }
        public string cdllicense { get; set; }
        public string tt6 { get; set; }
        public string recommend { get; set; }
        public string ywhynot { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string addr { get; set; }
        public string addr1 { get; set; }
        public string city { get; set; }
        public string C_state { get; set; }
        public string zip { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string company { get; set; }
        public Nullable<int> noofdrivers { get; set; }
        public string addfb { get; set; }
    }
}
