//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class hireus
    {
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string homephone { get; set; }
        public string placeofemp { get; set; }
        public string empphone { get; set; }
        public string email { get; set; }
        public string license { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string preferedby { get; set; }
        public string country { get; set; }
        public string legalprb { get; set; }
        public string token { get; set; }
        public int id { get; set; }
    }
}
