//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthClinic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class healthclinicEntities : DbContext
    {
        public healthclinicEntities()
            : base("name=healthclinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contactform> contactform { get; set; }
        public virtual DbSet<fleetservices> fleetservices { get; set; }
        public virtual DbSet<citations> citations { get; set; }
        public virtual DbSet<hireus> hireus { get; set; }
    }
}
